import { useEffect, useState } from 'react';
import { aiApi } from '../../services/api';
import { Card, CardHeader, CardTitle } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import PageHeader from '../../components/dashboard/PageHeader';

export default function StudentSuggestions() {
  const [items, setItems] = useState([]);

  useEffect(() => {
    aiApi.recommendations().then(({ data }) => setItems(data));
  }, []);

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI suggestions"
        description="Personalized recovery tips generated by Gemini through the recommendation agent."
      />
      {items.length === 0 ? (
        <Card><p className="text-muted-foreground text-sm">No recommendations yet. Ask admin to run AI workflow.</p></Card>
      ) : (
        items.map((rec) => (
          <Card key={rec._id}>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle>{new Date(rec.createdAt).toLocaleString()}</CardTitle>
              <Badge level={rec.riskStatus === 'high' ? 'red' : rec.riskStatus === 'medium' ? 'yellow' : 'green'}>
                {rec.riskStatus} risk
              </Badge>
            </CardHeader>
            {rec.summary && <p className="text-sm text-muted-foreground mb-3">{rec.summary}</p>}
            <ul className="list-disc pl-5 space-y-2 text-sm">
              {rec.items?.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
            {rec.classesNeededFor75 > 0 && (
              <p className="mt-4 text-sm text-amber-400">Classes needed for 75%: {rec.classesNeededFor75}</p>
            )}
          </Card>
        ))
      )}
    </div>
  );
}
